FROM {{ namespace }}/{{ image_prefix }}base:{{ tag }}
MAINTAINER {{ maintainer }}

{% block vspc_header %}{% endblock %}

{% if install_type == 'binary' %}

RUN echo '{{ install_type }} not yet available for {{ base_distro }}' \
    && /bin/false

{% elif install_type == 'source' %}

RUN apt-get update && apt-get install -y python3 python3-netifaces && apt-get -y clean && curl -O https://bootstrap.pypa.io/get-pip.py && python3 get-pip.py && rm get-pip.py && pip3 --no-cache-dir install git+https://github.com/openstack/vmware-vspc.git#egg=vmware-vspc \
    && useradd --user-group vspc \
    && apt-get clean \
    && rm -rf /tmp/* /var/tmp/*

{% endif %}

RUN usermod -a -G kolla vspc

{% block vspc_footer %}{% endblock %}
{% block footer %}{% endblock %}
{{ include_footer }}

USER vspc

