FROM {{ namespace }}/{{ image_prefix }}openstack-base:{{ tag }}

{% block vcenter_operator_header %}{% endblock %}

{% if install_type == 'binary' %}
RUN echo '{{ install_type }} not yet available for {{ base_distro }}' \
    && /bin/false

{% elif install_type == 'source' %}
RUN pip --no-cache-dir install 'git+https://github.com/sapcc/kubernetes-operators.git#egg=vcenter_operator&subdirectory=vcenter-operator' \
    && useradd --create-home --user-group -G kolla vcenter_operator && /bin/true

{% endif %}

{% block vcenter_operator_footer %}{% endblock %}
{% block footer %}{% endblock %}
{{ include_footer }}

USER vcenter_operator
