FROM {{ namespace }}/{{ image_prefix }}openstack-base:{{ tag }}
MAINTAINER {{ maintainer }}

{% block vcenter_operator_header %}{% endblock %}

{% if install_type == 'binary' %}

RUN echo '{{ install_type }} not yet available for {{ base_distro }}' \
    && /bin/false

{% elif install_type == 'source' %}

RUN pip --no-cache-dir install -c /requirements/upper-constraints.txt 'git+https://github.com/sapcc/kubernetes-operators.git@fwiesel-dev#egg=vcenter_operator&subdirectory=vcenter-operator' \
    && useradd --create-home --user-group -G kolla vcenter_operator

{% endif %}

ADD config.json /var/lib/kolla/config_files/config.json

{% block vcenter_operator_footer %}{% endblock %}
{% block footer %}{% endblock %}
{{ include_footer }}

USER vcenter_operator
