FROM {{ namespace }}/{{ image_prefix }}nova-base:{{ tag }}
MAINTAINER {{ maintainer }}

{% if install_type == 'binary' %}
    {% if base_distro in ['centos', 'fedora', 'oraclelinux', 'rhel'] %}

RUN yum -y install \
        novnc \
        openstack-nova-novncproxy \
    && yum clean all

    {% elif base_distro in ['ubuntu'] %}

RUN apt-get install -y --no-install-recommends \
        nova-novncproxy \
    && apt-get clean

    {% endif %}

{% endif %}
{% block nova_shellinaboxproxy_footer %}{% endblock %}

{% block footer %}{% endblock %}

USER nova
