FROM {{ namespace }}/{{ image_prefix }}barbican-base:{{ tag }}
MAINTAINER {{ maintainer }}

COPY extend_start.sh /usr/local/bin/kolla_barbican_extend_start
RUN chmod 755 /usr/local/bin/kolla_barbican_extend_start

{{ include_footer }}

USER barbican
