FROM {{ namespace }}/{{ image_prefix }}openstack-base:{{ tag }}
MAINTAINER {{ maintainer }}

{% if install_type == 'binary' %}
    {% if base_distro in ['centos', 'fedora', 'oraclelinux', 'rhel'] %}

RUN yum -y install \
        openstack-barbican \
    && yum clean all \
    && mkdir -p /etc/barbican/

    {% elif base_distro in ['ubuntu'] %}

RUN apt-get install -y --no-install-recommends \
        barbican \
        python-rbd \
        python-rados \
    && apt-get clean \
    && mkdir -p /etc/barbican/

    {% endif %}
{% elif install_type == 'source' %}
    {% if base_distro in ['centos', 'fedora', 'oraclelinux', 'rhel'] %}

RUN yum -y install \
    && yum clean all \
    && mkdir -p /etc/barbican/

    {% elif base_distro in ['ubuntu', 'debian'] %}

RUN apt-get install -y --no-install-recommends \
    && apt-get clean \
    && mkdir -p /etc/barbican/

    {% endif %}

ADD barbican-base-archive /barbican-base-source
RUN ln -s barbican-base-source/* barbican \
    && useradd --user-group barbican \
    && pip install -c requirements/upper-constraints.txt -e /barbican && rm -fr /root/.cache \
    && mkdir -p /etc/barbican /var/lib/barbican /home/barbican \
    && cp -r /barbican/etc/* /etc/barbican/ \
    && chown -R barbican: /etc/barbican /var/lib/barbican /home/barbican

{% endif %}

COPY barbican_sudoers /etc/sudoers.d/kolla_barbican_sudoers
COPY extend_start.sh /usr/local/bin/kolla_extend_start

RUN usermod -a -G kolla barbican \
    && chmod 750 /etc/sudoers.d \
    && chmod 440 /etc/sudoers.d/kolla_barbican_sudoers \
    && touch /usr/local/bin/kolla_barbican_extend_start \
    && chmod 755 /usr/local/bin/kolla_extend_start /usr/local/bin/kolla_barbican_extend_start
